<?php 
/********************************************************************************* 
 *  This file is part of Camhrms.
 *  Copyright (C) 2014 AAP
 *   
 *  Camhrms is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Camhrms is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Camhrms.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Camhrms Support <support@camtech-indponesia.co.id>
 ********************************************************************************/
?>

<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
    <div style='padding:20px 0 0 0;color:#3b3b3b;'>
    	Your SignalBit - HR account has been made inactive. Your user id is <?php echo $this->user_id;?> and your last login was on <?php echo $this->print_date;?>. 
    </div>
</div>      
	  
