<?php 

?>

<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
	<span style='color:#3b3b3b;'>Hello <?php echo ucfirst($this->emp_name);?>,</span><br />
	
	<div style='padding:20px 0 0 0;color:#3b3b3b;'>You have been added to <?php echo APPLICATION_NAME; ?>. The login credentials for your SIGNALBIT-HR account are:</div>
	
	<div style='padding:20px 0 0 0;color:#3b3b3b;'>Username: <strong><?php echo $this->emp_id;?></strong></div>
	<div style='padding:5px 0 0 0;color:#3b3b3b;'>Password: <strong><?php echo $this->password;?></strong></div>
	
	<div style="padding:20px 0 10px 0;">Please <a href="<?php echo BASE_URL;?>" target="_blank" style="color:#b3512f;">click here</a> to login  to your SIGNALBIT-HR account.</div>

</div>      
      
