<?php 
/********************************************************************************* 
 *  This file is part of Camhrms.
 *  Copyright (C) 2014 AAP
 *   
 *  Camhrms is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Camhrms is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Camhrms.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Camhrms Support <support@camtech-indponesia.co.id>
 ********************************************************************************/
?>

<?php 
$options_data = "";	

	if($this->flag != 'true')
	{
            $options_data .= sapp_Global::selectOptionBuilder('', 'Select A Reporting Manager');
		foreach ($this->RMdata as $opt) {
			$options_data .= sapp_Global::selectOptionBuilder($opt['id'],ucwords(utf8_encode($opt['name'])),$opt['profileimg'] );
		}
		echo $options_data;
	}
	else
	{
	    echo "nomanagers";
	}

?> 
 