<?php 
/********************************************************************************* 
 *  This file is part of Camhrms.
 *  Copyright (C) 2014 AAP
 *   
 *  Camhrms is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Camhrms is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Camhrms.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Camhrms Support <support@camtech-indponesia.co.id>
 ********************************************************************************/
?>

<?php  $options_data = "";
   $options_data .= sapp_Global::selectOptionBuilder('', 'Select Category ');
if(!empty($this->user_cat_data))
{
		foreach ($this->user_cat_data as $userdata) {
			$options_data .= sapp_Global::selectOptionBuilder($userdata['id'],utf8_encode($userdata['name']));
			
		}
		echo $options_data;
	
}else
{
  echo "nocategories";
} 
?> 
 